services:
  train:
    build: .
    volumes:
      - ${TRAIN_DIR}:/data/images
      - ${TRAIN_FILE}:/data/masks.csv
      - ${PARAMETERS_FILE}:/data/model.keras
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    command: python train.py