services:
  jupyter:
    build: .
    volumes:
      - ${TRAIN_DIR}:/data/images
      - ${TRAIN_FILE}:/data/masks.csv
      - ./data-analysis.ipynb:/app/data-analysis.ipynb
    ports:
      - "8888:8888"
    command: jupyter notebook --ip 0.0.0.0 --no-browser --allow-root